# Generated by Django 4.2 on 2023-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=100)),
            ],
        ),
    ]
